name: Go
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.22.6'
                
            - name: Install dependencies
              working-directory: ./backend
              run: go mod download
              
            - name: Build
              working-directory: ./backend
              run: go build -v ./...

            - name: Run tests
              working-directory: ./backend
              run: go test -v ./tests/...